services:
  api:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./.env
  postgres-db:
    image: postgres
    env_file:
      - ./db.env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
