services:
  postgres-db:
    image: postgres
    env_file:
      - ./db.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
  api:
    image: rmall67/fastapi-template
    ports:
      - 3000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres-db
    networks:
      - app-network
volumes:
  pg_data:
networks:
  app-network:
