services:
  postgres-db:
    image: postgres
    env_file:
      - ./db.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
  api:
    build: .
    ports:
      - 3000:8000
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres-db
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
